// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqgrnfcaxivngjqjruvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZ3JuZmNheGl2bmdqcWpydXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MjM2MDksImV4cCI6MjA2MTI5OTYwOX0.sWT4wPzidSZw_NpV78cNhRzNLiUBqIlr8aHQJI5kDXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);