
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Tests
      run: npm test -- --coverage
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      
    - name: Lint Code
      run: npm run lint
      
    - name: Build Project
      run: npm run build

  issue-automation:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
    - name: Auto-label issues
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue = context.payload.issue;
          const title = issue.title.toLowerCase();
          
          // Automatically label issues based on keywords in title
          const labelMap = {
            'bug': ['erro', 'falha', 'correção', 'fix', 'bug'],
            'enhancement': ['melhoria', 'aprimorar', 'feature', 'novo', 'implementar'],
            'frontend': ['ui', 'interface', 'design', 'css', 'componente'],
            'backend': ['api', 'banco', 'database', 'servidor', 'autenticação'],
            'documentation': ['doc', 'documentação', 'readme'],
            'test': ['teste', 'testing', 'unit test', 'e2e']
          };
          
          const labelsToAdd = [];
          
          for (const [label, keywords] of Object.entries(labelMap)) {
            if (keywords.some(keyword => title.includes(keyword))) {
              labelsToAdd.push(label);
            }
          }
          
          if (labelsToAdd.length > 0) {
            await github.rest.issues.addLabels({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labelsToAdd
            });
          }
          
          // For newly opened issues, add to project if it's not already added
          if (context.payload.action === 'opened') {
            // Note: You'll need to configure your project ID
            // This is a placeholder for the actual project ID
            console.log('New issue opened:', issue.title);
          }
